python_preprocessing_analyze_electrophysiology_data/analyze_electrophysiology_data/urls.py
from django.conf import settings
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('pl2kilosort/', include('pl2kilosort.urls')),
    path('psth/', include('psth.urls')),
    path('mapping/', include('mapping.urls')),
    path('brain_render/', include('brain_render.urls')),
    path('clustering/', include('clustering.urls')),
    path('admin/', admin.site.urls),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python_preprocessing_analyze_electrophysiology_data/psth/urls.py
from django.urls import path

from . import views

app_name = 'psth'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

python_preprocessing_analyze_electrophysiology_data/psth/models.py
from django.db import models


class Analysis(models.Model):
    TRIAL_TYPES = [
        #('individual', 'Individual'), 
        ('sequence', 'Sequence'),
    ]
    UNIT_TYPES = [
        #('1', 'Multi Units'), 
        ('2', 'Single Units'),
    ]
    
    trial_type = models.CharField(max_length=15, choices=TRIAL_TYPES)
    unit_type = models.CharField(max_length=15, choices=UNIT_TYPES)
    standardize = models.BooleanField(default=True, null=True, blank=True)
    length_of_trial = models.IntegerField(blank=False, null=True)
    bin_length = models.IntegerField(blank=False, null=True)
    split_chunks = models.CharField(max_length=5000, blank=True, null=True)
    remove_low_baseline_clusters = models.BooleanField(default=True, null=True, blank=True)
    remove_high_movement_correlation = models.BooleanField(default=True, null=True, blank=True)

python_preprocessing_analyze_electrophysiology_data/psth/forms.py
from django import forms
from django.forms import ModelForm

from .models import Analysis


class PsthAnalysisForm(ModelForm):
    trial_type = forms.CharField(
        max_length=15,
        widget=forms.Select(choices=Analysis.TRIAL_TYPES),
        required=True,
    )
    unit_type = forms.CharField(
        max_length=15,
        widget=forms.Select(choices=Analysis.UNIT_TYPES),
        required=True,
    )
    standardize = forms.BooleanField(initial=True, required=False)
    length_of_trial = forms.IntegerField(initial=20000, min_value=1, label='Trial length in ms', required=True)
    bin_length = forms.IntegerField(initial=100, min_value=1, label='Bin length in ms', required=True)
    remove_low_baseline_clusters = forms.BooleanField(initial=True, required=False)
    remove_high_movement_correlation = forms.BooleanField(initial=True, required=False)
    
    class Meta:
        model = Analysis
        fields = '__all__'

python_preprocessing_analyze_electrophysiology_data/psth/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic.edit import FormView
from django.core.exceptions import ValidationError

from .forms import PsthAnalysisForm
from .models import Analysis
from .psth_analysis import psth


class IndexView(FormView):
    model = Analysis
    form_class = PsthAnalysisForm
    template_name = 'psth/index.html'
    success_url = 'psth/index.html'
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if form.is_valid():
            standardize = True if form.cleaned_data['standardize'] else False
            remove_low_baseline_clusters = True if form.cleaned_data['remove_low_baseline_clusters'] else False
            remove_high_movement_correlation = True if form.cleaned_data['remove_high_movement_correlation'] else False
            trial_type = request.POST['trial_type']
            unit_type = form.cleaned_data['unit_type']
            length_of_trial = int(request.POST['length_of_trial'])
            bin_length = int(request.POST['bin_length'])
            split_chunks = request.POST['split_chunks']
            message = psth(standardize, remove_low_baseline_clusters, trial_type, unit_type, length_of_trial, bin_length, split_chunks, remove_high_movement_correlation)
            messages.add_message(request, messages.SUCCESS, 'Completed successfully')
            messages.add_message(request, messages.INFO, message)
        else:
            form.add_error(None, 'Something went wrong')
            return super().form_invalid(form)
            
        return render(request, self.success_url, {'form': form})

python_preprocessing_analyze_electrophysiology_data/psth/templates/psth/index.html
{% extends "base.html" %}
{% load materializecss %}


{% block css %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}

{% block title %}
{% endblock title %}

{% block content %}

{% if messages %}
	{% for message in messages %}
		{% if 'success' in message.tags %}
			<div name="messages-card" class="card-panel bg-success text-white fs-5 lighten-2" color="">{{ message }}</div>
		{% elif 'info' in message.tags %}
			<div name="messages-card" class="card-panel bg-info text-white fs-5 lighten-2">{{ message }}</div>
		{% endif %}
	{% endfor %}
{% endif %}


<h2>PSTH Analysis</h2>
<form id="form" action="{% url 'psth:index' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
    {{ form|materializecss  }}
	<br>
	<button id="submit-btn" type="submit" class="waves-effect waves light btn-large">Analyze PSTH</button>
	<br>
	<br>
	<div id="progress-box" class="not-visible"></div>
</form>
{% endblock content %}

{% block scripts %}
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

  // Initialize materialize data picker
  $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
  $('select').formSelect();

});
</script>
{% endblock scripts %}