python_preprocessing_analyze_electrophysiology_data/analyze_electrophysiology_data/urls.py
from django.conf import settings
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('pl2kilosort/', include('pl2kilosort.urls')),
    path('psth/', include('psth.urls')),
    path('mapping/', include('mapping.urls')),
    path('brain_render/', include('brain_render.urls')),
    path('clustering/', include('clustering.urls')),
    path('admin/', admin.site.urls),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

python_preprocessing_analyze_electrophysiology_data/pl2kilosort/urls.py
from django.urls import path

from . import views

app_name = 'pl2kilosort'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

python_preprocessing_analyze_electrophysiology_data/psth/urls.py
from django.urls import path

from . import views

app_name = 'psth'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

python_preprocessing_analyze_electrophysiology_data/pl2kilosort/models.py
import os

from django.db import models
from django.conf import settings


def get_upload_path(instance, filename):
    return '/'.join(filter(None, ('pl2kilosort/files', instance.trial_type, filename)))

class Trial(models.Model):
    TYPES = [
        #('individual', 'Individual'), 
        ('sequence', 'Sequence'),
    ]
    
    INTENSITIES_NUMBER = [ 
        ('7', '7'),
        ('10', '10'),
    ]
    
    trial_type = models.CharField(max_length=15, choices=TYPES)
    intensities_number = models.CharField(max_length=10, choices=INTENSITIES_NUMBER)
    matlab_files = models.FileField(upload_to=get_upload_path, blank=False, null=True)
    plexon_files = models.FileField(upload_to=get_upload_path, blank=False, null=True)
    
    def __str__(self):
        return self.trial_type
        
 

python_preprocessing_analyze_electrophysiology_data/pl2kilosort/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from .models import Trial


class Pl2KilosortForm(ModelForm):
    trial_type = forms.CharField(
        max_length=15,
        widget=forms.Select(choices=Trial.TYPES),
        required=True,
    )
    intensities_number = forms.CharField(
        max_length=10,
        widget=forms.Select(choices=Trial.INTENSITIES_NUMBER),
        required=True,
    )
    matlab_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=True)
    plexon_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=True)
    
    class Meta:
        model = Trial
        fields = '__all__'

    def clean_matlab_files(self):
        data = self.cleaned_data['matlab_files']

        if not data.name.endswith('.mat'):
            raise ValidationError('Invalid file type - needs to be a .mat file')

        return data
    
    def clean_plexon_files(self):
        data = self.cleaned_data['plexon_files']
    
        if not data.name.endswith('.pl2'):
            raise ValidationError('Invalid file type - needs to be a .pl2 file')

        return data

python_preprocessing_analyze_electrophysiology_data/pl2kilosort/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic.edit import FormView
from django.core.exceptions import ValidationError

from .forms import Pl2KilosortForm
from .models import Trial
from .pl2kilosort_code import pl2kilosort


class IndexView(FormView):
    model = Trial
    form_class = Pl2KilosortForm
    template_name = 'pl2kilosort/index.html'
    success_url = 'pl2kilosort/index.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class) 
        matlab_files = request.FILES.getlist('matlab_files')
        plexon_files = request.FILES.getlist('plexon_files')
        
        if form.is_valid():
            trial_type = request.POST['trial_type']
            intensities_number = request.POST['intensities_number']
            [Trial(matlab_files=f, trial_type=trial_type).save() for f in matlab_files]
            [Trial(plexon_files=f, trial_type=trial_type).save() for f in plexon_files]
            pl2kilosort(trial_type, intensities_number)
            messages.add_message(request, messages.SUCCESS, 'Completed successfully')
        else:
            form.add_error(None, 'Something went wrong')
            return super().form_invalid(form)
            
        return render(request, self.success_url, {'form': form})

python_preprocessing_analyze_electrophysiology_data/pl2kilosort/templates/pl2kilosort/index.html
{% extends "base.html" %}
{% load materializecss %}


{% block css %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
{% endblock css %}

{% block title %}
{% endblock title %}

{% block content %}

{% if messages %}
	{% for message in messages %}
		{% if 'success' in message.tags %}
			<div id="messages-card" class="card-panel bg-success text-white fs-5 lighten-2">{{ message }}</div>
		{% endif %}
	{% endfor %}
{% endif %}


<h2>Trial Analysis</h2>
<form id="form" action="{% url 'pl2kilosort:index' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	
    {{ form|materializecss  }}
	<br>
	<button id="submit-btn" type="submit" class="waves-effect waves light btn-large">Submit</button>
	<br>
	<br>
	<div id="progress-box" class="not-visible"></div>
</form>
{% endblock content %}

{% block scripts %}
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js" integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

<script>
$(document).ready(function(){

  // Initialize materialize data picker
  $('.datepicker').datepicker({'format': 'yyyy-mm-dd'});
  $('select').formSelect();

});
</script>
{% endblock scripts %}